[package]
name = "magik"
version = "0.1.0"
edition = "2021"

[dependencies]
argparse = "0.2.2"
indicatif = { version = "0.17.7", features = ["rayon"] }
itertools = "0.11.0"
rayon = "1.8.0"
tokio = { version = "1.36.0", features = ["fs", "rt-multi-thread", "io-std", "io-util"] }
